### ISSUE TITLE
add diagonal folds?

### ISSUE THREAD

**Issue by cybertheory** [dasRicardo/flutter_paperfold#2]
hey this is a great effect, want to use it in my project. Anyway, we can work on adding diagonal folding?

**Comment by dasRicardo** [comment]
Hello,

i don't know exactly what do expect visually? Can u show me how should this look like.  Should only the fold diagonal or your content also? (If so, u can simply wrap the widget with a transform widget). 
If only the fold is diagonal then it will be difficult if your content is not a square. How should it look like?

**Comment by cybertheory** [comment]
hi sorry for late response
something like this
![personal-sticky-blue](https://github.com/dasRicardo/flutter_paperfold/assets/27149047/3b0f22f9-3b6d-49d8-b6dc-45e44ae6cb8a)

**Comment by dasRicardo** [comment]
if u want this effect u don't need paperfold for this. A simple custom Painter can achieve this for u. A mask to remove the unwanted area. Paperfold can't achieve this effect and wouldn't look like this.
