### ISSUE TITLE
Fold Animation Breaks When Starting at 0

### ISSUE THREAD

**Issue by SpongeManiac** [dasRicardo/flutter_paperfold#3]
Hello, I am having an issue on web with this animation. If the widget's fold value starts at 0.0, the animation breaks, however, when the animation start at any value other than 0.0, it works as expected. Right now, I'm resorting to using a very small number (0.001) instead of absolute zero.

**Comment by dasRicardo** [comment]
Hello,

I apologize for my late reply. I think I was able to fix the bug, but I would like to test if it is really fixed before I make a new release. Would it be possible for you to clone the current main branch and then test the plugin locally via a path dependency in your project?

Many thanks for your efforts in advance
